project:
    type: website
    output-dir: _slides
    render:
      - index.qmd

format:
  revealjs:
    theme: simple
    slideNumber: true
    slide-level: 3
    toc: true
    toc-title: "Contents"
    toc-depth: 1
    toc-expand: 2
    
editor:
  console: true
  markdown:
    wrap: 72
    canonical: true
    
# editor_options:
  chunk_output_type: console
    
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-browser --no-render --no-prompt