# Changes over time

- [Population](#changes-population)

```{r}
#| output: false
#| eval: true

# get data ----
# acs_data <- readRDS(fs::path(ddir, "acs_data.rds"))
pop <- readRDS(fs::path(ddir, "population", "county_population.rds"))

```


## Changes: Population


### A half-century of population data

```{r}
#| label: population-levels

counties <- c("36083", "36091", "36113", "36115")

capt <-  "\nSource: U.S. Census Bureau and NYS Department of Labor"

pop |> 
  filter(geoid %in% counties) |>
  mutate(ipop=pop / pop[year==2015],
         cpcpop = ipop * 100 - 100,
         .by=geoid) |>
  ggplot(aes(x=year, y=pop / 1000)) +
  geom_line(colour = "blue", linewidth = 1) +
  scale_x_continuous(name = NULL, breaks = seq(1900, 2025, 5)) +
  scale_y_continuous(name = "Population (thousands)") +
  ggtitle(label="Population in area counties") +
  labs(caption = capt) +
  theme_minimal() +
  legend_notitle +
  caption_left +
  facet_wrap(~trimname, scales="free_y")

```


### Population declines in Washington County have been persistent and severe

```{r}
#| label: population-changes

counties <- c("36083", "36091", "36113", "36115")

capt1 <-  "Source: U.S. Census Bureau and NYS Department of Labor"
capt2 <- "Note: Bump in 2020 reflects 2020 decennal census break from prior estimates"
capt <- paste0("\n", capt1, "\n", capt2)

baseyear <- 2010
pop |> 
  filter(geoid %in% counties) |>
  mutate(ipop=pop / pop[year==baseyear],
         cpcpop = ipop * 100 - 100,
         .by=geoid) |>
  filter(year >= baseyear) |>
  ggplot(aes(x=year, y=cpcpop, colour=trimname)) +
  geom_line(linewidth = 1) +
  geom_hline(yintercept = 0, linetype="solid", linewidth = .5) +
  scale_x_continuous(name = NULL, breaks = seq(baseyear, 2025, 1)) +
  scale_y_continuous(name = "Cumulative percentage change",
                     breaks =  seq(-20, 20, 1),
                     labels=scales::comma_format()) +
  ggtitle(label=paste0("Cumulative percentage change in population since ", baseyear)) +
  labs(caption = capt) +
  theme_minimal() +
  legend_notitle +
  caption_left

```

