# Demographics

- [Age](#demographics-age)

- [Educational attainment](#demographics-educational-attainment)


```{r}
#| output: false

# get acs data ----
acs_data <- readRDS(fs::path(ddir, "acs_data.rds"))
count(acs_data, variable, concept, label)

```


## Demographics: Age

### Washington County is older than most area counties


```{r}
#| label: plot_age_county

special <- "36115"
data <- acs_data |> 
  filter(variable == "B01002_001", geotype == "county", geoid %in% keep_cos) |> 
  mutate(special=geoid==special)

yint <- data |> filter(special) |> pull(estimate)

barline(data, "Median age, selected area counties", "Median age", seq(0, 100, 5), yint)

```

### Cambridge village is older than nearby places

```{r}
#| label: plot_age_place

special <- "3611825"

data <- acs_data |> 
  filter(variable == "B01002_001", geotype == "place", geoid %in% keep_places) |> 
  mutate(special=geoid==special)


yint <- data |> filter(special) |> pull(estimate)

barline(data, "Median age, selected area villages and places", "Median age", seq(0, 100, 5), yint)

```

::: {style="font-size: 0.4em;"}
Caveat: Perhaps this reflects a concentration of senior housing?
:::


### Jackson and White Creek towns are older than nearby towns

```{r}
#| label: plot_age_cousub

special <- "3611511836"

data <- acs_data |> 
  filter(variable == "B01002_001", geotype == "cousub", geoid %in% keep_cousubs) |> 
  mutate(special=geoid==special)

yint <- data |> filter(special) |> pull(estimate)

barline(data, "Median age, selected area towns", "Median age", seq(0, 100, 5), yint)

```


