
# Economy

## Income and Poverty {.unlisted}

```{r}
#| output: false

# get acs data ----
acs_data <- readRDS(fs::path(ddir, "acs_data.rds"))
count(acs_data, variable, concept, label)

```

### Washington County has lower household income than most area counties

```{r}
#| label: plot_income_county

special <- "36115"
data <- acs_data |> 
  filter(variable == "B19013_001", geotype == "county", geoid %in% keep_cos) |> 
  mutate(special=geoid==special)

yint <- data |> filter(special) |> pull(estimate)

barline(data, "Median household income, selected area counties", "Dollars", seq(0, 100e3, 5e3), yint)

```

### Cambridge village household income is about middle for nearby places

```{r}
#| label: plot_income_place

special <- "3611825"
data <- acs_data |> 
  filter(variable == "B19013_001", geotype == "place", geoid %in% keep_places) |> 
  mutate(special=geoid==special)

yint <- data |> filter(special) |> pull(estimate)

barline(data, "Median household income, selected area villages and places", "Dollars", seq(0, 100e3, 5e3), yint)

```


### Cambridge town household income is higher than nearby towns

```{r}
#| label: plot_income_cousub

special <- "3611511836"

data <- acs_data |> 
  filter(variable == "B19013_001", geotype == "cousub", geoid %in% keep_cousubs) |> 
  mutate(special=geoid==special)

yint <- data |> filter(special) |> pull(estimate)

barline(data, "Median household income, selected area towns", "Dollars", seq(0, 100e3, 5e3), yint)

```


